---

- name: Ensure firewall service
  ansible.posix.firewalld:
    service: RH-Satellite-6
    permanent: true
    state: enabled
    immediate: true

- name: Add 8443/tcp to Capsules
  ansible.posix.firewalld:
    service: RH-Satellite-6-capsule
    permanent: true
    state: enabled
    immediate: true
  when:
    - groups['capsules'] is defined
    - inventory_hostname in groups['capsules']
