---

- name: Install packages for satellite
  ansible.builtin.yum:
    name: satellite
    state: present
  when:
    - groups['satellite'] is defined
    - inventory_hostname in groups['satellite']

- name: Install packages for satellite-capsule
  ansible.builtin.yum:
    name: satellite-capsule
    state: present
  when:
    - groups['capsules'] is defined
    - inventory_hostname in groups['capsules']
