---

- name: Set Repositories for Respective RHEL Version
  ansible.builtin.include_tasks:
    file: set-repositories-for-rhel{{ ansible_distribution_major_version }}.yml

- name: Enable Repositories
  ansible.builtin.import_tasks: configure-repositories.yml

- name: Remove conflicting RPMs
  ansible.builtin.import_tasks: remove-conflicting-rpms.yml

- name: Install RPMs
  ansible.builtin.import_tasks: install-satellite-rpms.yml

- name: Import Firewall Tasks
  ansible.builtin.import_tasks: firewall.yml

- name: Set Satellite Master Install Settings
  ansible.builtin.include_tasks: set-initial-install-settings.yml
  when:
    - "'satellite' in group_names"

- name: Import Satellite Install Tasks
  ansible.builtin.include_tasks: run-satellite-installer.yml
  when:
    - "'satellite' in group_names"

- name: Import Capsule Install Tasks
  ansible.builtin.include_tasks: capsule.yml
  when:
    - "'capsule' in group_names"
