---

- name: Configure Repositories
  ansible.builtin.import_tasks: configure-repositories.yml

- name: Remove conflicting RPMs
  ansible.builtin.import_tasks: remove-conflicting-rpms.yml

- name: Install RPMs
  ansible.builtin.import_tasks: install-satellite-rpms.yml

- name: Import Firewall Tasks
  ansible.builtin.import_tasks: firewall.yml

- name: Set Satellite Master Install Settings
  ansible.builtin.import_tasks: set-initial-install-settings.yml
  when:
    - inventory_hostname in groups['satellite']

- name: Import Satellite Install Tasks
  ansible.builtin.import_tasks: run-satellite-installer.yml
  when:
    - inventory_hostname in groups['satellite']

- name: Import Capsule Install Tasks
  ansible.builtin.import_tasks: capsule.yml
  when:
    - inventory_hostname in groups['capsules']
