---

- name: set initial foreman organization
  set_fact:
    satellite_initial_organization: "{{ organization.name }}"
  when:
    - organization.initial_organization is defined
    - organization.initial_organization
  loop_control:
    loop_var: organization
  loop: "{{ satellite.foreman.organizations }}"

- name: set initial foreman location
  set_fact:
    satellite_initial_location: "{{ location.name }}"
  when:
    - location.initial_location is defined
    - location.initial_location
  loop_control:
    loop_var: location
  loop: "{{ satellite.foreman.locations }}"

- name: gather up initial installer options
  set_fact:
    satellite_installer_options: "--foreman-initial-admin-username '{{ satellite.admin_username }}' --foreman-initial-admin-password '{{ satellite.admin_password }}' --foreman-initial-organization '{{ satellite_initial_organization }}' --foreman-initial-location '{{ satellite_initial_location }}'"

- name: append tuning profile
  set_fact:
    satellite_installer_options: "{{ satellite_installer_options }} --tuning '{{ satellite.tuning_profile }}'"
  when:
    - satellite.tuning_profile is defined

- name: append additional installer options
  set_fact:
    satellite_installer_options: "{{ satellite_installer_options }} {{ satellite.installer_options | join(' ') }}"
  when: satellite.installer_options is defined

- name: create directory for options file
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
  loop_control:
    loop_var: directory
  loop:
    - /root/satellite
    - "/root/satellite/{{ inventory_hostname }}/certificates"

- name: Create options file
  ansible.builtin.copy:
    content: "{{ satellite_installer_options }}"
    dest: /root/satellite/options
    owner: root
    group: root
    mode: 0600
    backup: yes
  when:
    - satellite_installer_options is defined
  register: satellite_options_file
