namespace: jjaswanson4
name: install_satellite
version: 1.0.0
readme: README.md
authors:
- Josh Swanson <jswanson@redhat.com>
- Scott Danielson <sdaniels@redhat.com>
- Rodrique Heron <rheron@redhat.com>
description: This collection installs satellite6
license:
- GPL-2.0-or-later
tags:
  - satellite6
  - install_satellite
#dependencies:
#  "jjaswanson4.setup_for_satellite": "*"
repository: https://github.com/jjaswanson4/install_satellite
documentation: https://github.com/jjaswanson4/install_satellite/blob/master/README.md
homepage: https://github.com/jjaswanson4/install_satellite
issues: https://github.com/jjaswanson4/install_satellite/issues
